[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lintfix]
# toolchain = "nightly"
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty", "--allow-staged"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.devtest]
dependencies = [
    "lintfix",
    "format",
    "test",
]

[tasks.bench]
toolchain = "nightly"
command = "cargo"
args = ["bench", "--features", "nightly", "--benches"]
