edition = "2024"

fn_params_layout = "Vertical"
newline_style = "Unix"

# unstable/nightly
# format_code_in_doc_comments = true
# doc_comment_code_block_width = 80
# format_macro_matchers = true
# imports_layout = "HorizontalVertical"
